FROM python:3

ENV PYTHONNUNBUFFERED 1

ENV DISCORD_TOKEN YOUR_DISCORD_TOKEN
ENV DISCORD_GUILD YOUR_DISCORD_GUILD
ENV REDDIT_USER YOUR_REDDIT_USER
ENV REDDIT_PASSWORD YOUR_REDDIT_PASSWORD
ENV CLIENT_ID YOUR_CLIENT_ID
ENV CLIENT_SECRET YOUR_CLIENT_SECRET

RUN mkdir /bot-code
WORKDIR /bot-code
ADD . /bot-code

RUN apt-get update
RUN pip install -r requirements.txt

CMD ["main.py"]
ENTRYPOINT ["python3"]