services:
  gogig:
    build: ghcr.io/tech-dex/GoGig:latest
    container_name: gogig
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      - db_network

networks:
  db_network:
    external: true
    name: db_network
